/*
 * queryGuestRoomInfo.java
 *
 * Created on __DATE__, __TIME__
 */

package hotel.view;

import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.sun.org.apache.bcel.internal.generic.NEW;

import hotel.dao.BianJiDao;
import hotel.dao.KeFangDao;
import hotel.model.KeFang;
import hotel.util.DbUtil;

/**
 *
 * @author  __USER__
 */
public class queryGuestRoomInfo extends javax.swing.JInternalFrame {

	DbUtil dbUtil = new DbUtil();
	BianJiDao editModulDao = new BianJiDao();
	KeFangDao guestRoomDao = new KeFangDao();

	/** Creates new form queryGuestRoomInfo */
	public queryGuestRoomInfo() {
		initComponents();

		String roomNum = null;
		this.fillTable(roomNum);
		this.setLocation(200, 50);//设置窗口位置
	}

	/**
	 * 填充表格数据
	 * @param name
	 */
	public void fillTable(String roomNum) {
		DefaultTableModel dtm = (DefaultTableModel) queryGuestRoomInfoTable
				.getModel();
		dtm.setRowCount(0);
		Connection con = null;
		try {
			con = dbUtil.getCon();
			ResultSet re = editModulDao.findGuestRoomState(con, roomNum);
			while (re.next()) {
				Vector v = new Vector();
				//添加每一行的数据
				v.add(re.getString("id"));
				v.add(re.getString("num"));
				v.add(re.getString("type"));
				String state = re.getString("state");
				if (state.equals("0")) {
					state = "未入住";
				} else {
					state = "入住中";
				}
				v.add(state);
				dtm.addRow(v);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			try {
				dbUtil.closeCon(con);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		roomNum = new javax.swing.JTextField();
		search = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		queryGuestRoomInfoTable = new javax.swing.JTable();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		reRoomNum = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		state = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		type = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		id = new javax.swing.JTextField();
		editBtn = new javax.swing.JButton();

		setClosable(true);
		setIconifiable(true);
		setTitle("\u67e5\u8be2\u5ba2\u623f\u4fe1\u606f");

		jLabel1.setText("\u623f\u95f4\u53f7");

		search.setText("\u67e5\u8be2");
		search.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				searchActionPerformed(evt);
			}
		});

		queryGuestRoomInfoTable
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null },
								{ null, null, null, null },
								{ null, null, null, null },
								{ null, null, null, null } }, new String[] {
								"编号", "房间号", "房间类型", "状态" }) {
					boolean[] canEdit = new boolean[] { false, false, false,
							false };

					public boolean isCellEditable(int rowIndex, int columnIndex) {
						return canEdit[columnIndex];
					}
				});
		queryGuestRoomInfoTable
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mousePressed(java.awt.event.MouseEvent evt) {
						queryGuestRoomInfoTableMousePressed(evt);
					}
				});
		jScrollPane1.setViewportView(queryGuestRoomInfoTable);

		jLabel2.setText("\u7f16\u8f91\u5ba2\u623f\u4fe1\u606f");

		jLabel3.setText("\u623f\u95f4\u53f7");

		reRoomNum.setEditable(false);

		jLabel4.setText("\u7c7b\u578b");

		jLabel5.setText("\u72b6\u6001");

		jLabel6
				.setText("*\u8bf7\u586b\u5199\u672a\u5165\u4f4f\u3001\u5165\u4f4f\u4e2d");

		jLabel7.setText("\u7f16\u53f7");

		id.setEditable(false);

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jLabel2)
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				5,
																				5,
																				5)
																		.add(
																				jPanel1Layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								jPanel1Layout
																										.createSequentialGroup()
																										.add(
																												10,
																												10,
																												10)
																										.add(
																												jLabel5))
																						.add(
																								jLabel3))
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jPanel1Layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING,
																								false)
																						.add(
																								state)
																						.add(
																								reRoomNum,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								143,
																								Short.MAX_VALUE))
																		.add(
																				jPanel1Layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED,
																												70,
																												Short.MAX_VALUE)
																										.add(
																												jLabel6)
																										.add(
																												86,
																												86,
																												86))
																						.add(
																								jPanel1Layout
																										.createSequentialGroup()
																										.add(
																												29,
																												29,
																												29)
																										.add(
																												jLabel4)
																										.add(
																												18,
																												18,
																												18)
																										.add(
																												type,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												154,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jLabel7)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(
												id,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												46,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(jLabel2)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel3)
														.add(
																reRoomNum,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel4)
														.add(
																type,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel7)
														.add(
																id,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel5)
														.add(jLabel6)
														.add(
																state,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(35, Short.MAX_VALUE)));

		editBtn.setText("\u7f16\u8f91");
		editBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				editBtnActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().add(23, 23, 23).add(jLabel1)
						.add(18, 18, 18).add(roomNum,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								167,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.add(18, 18, 18).add(search).addContainerGap()).add(
				layout.createSequentialGroup().addContainerGap().add(
						jScrollPane1,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 920,
						Short.MAX_VALUE)).add(
				layout.createSequentialGroup().add(37, 37, 37).add(editBtn)
						.addContainerGap(838, Short.MAX_VALUE)).add(
				layout.createSequentialGroup().addContainerGap().add(jPanel1,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(356, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().add(35, 35, 35).add(
						layout.createParallelGroup(
								org.jdesktop.layout.GroupLayout.BASELINE).add(
								jLabel1).add(roomNum,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(search)).addPreferredGap(
						org.jdesktop.layout.LayoutStyle.RELATED,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE).add(jScrollPane1,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED).add(
								jPanel1,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.UNRELATED).add(
								editBtn).add(8, 8, 8)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void searchActionPerformed(java.awt.event.ActionEvent evt) {
		String roomNum = this.roomNum.getText();
		this.fillTable(roomNum);
	}

	private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {
		String roomNum = this.reRoomNum.getText();
		String type = this.type.getText();
		String state = this.state.getText();
		if ("".equals(roomNum) || roomNum == null) {
			JOptionPane.showMessageDialog(null, "房间号不能为空");
			return;
		}
		if ("".equals(type) || type == null) {
			JOptionPane.showMessageDialog(null, "类型不能为空");
			return;
		}
		if ("".equals(state) || state == null) {
			JOptionPane.showMessageDialog(null, "状态不能为空");
			return;
		}
		if (!"入住中".equals(state)) {
			JOptionPane.showMessageDialog(null, "请输入正确的状态");
			return;
		}
		if ("未入住".equals(state) || "入住中".equals(state)) {
			int reState = 0;
			if("入住中".equals(state)){
				reState = 1;
			}
			
			KeFang guestRoom = new KeFang();
			guestRoom.setNum(Integer.parseInt(roomNum));
			guestRoom.setState(reState);
			guestRoom.setType(type);
			guestRoom.setId(Integer.parseInt(this.id.getText()));
			Connection con = null;
			try {
				con = dbUtil.getCon();
				int result = editModulDao.updateGuestRoom(con, guestRoom);
				if (result != 0) {
					JOptionPane.showMessageDialog(null, "修改成功");
					String num = null;
					this.fillTable(num);
				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		} else {
			JOptionPane.showMessageDialog(null, "请输入正确的状态");
			return;
		}

	}

	/**
	 * 鼠标点击事件
	 */
	private void queryGuestRoomInfoTableMousePressed(
			java.awt.event.MouseEvent evt) {
		//获取选择的行
		int row = queryGuestRoomInfoTable.getSelectedRow();
		this.reRoomNum.setText(queryGuestRoomInfoTable.getValueAt(row, 1)
				.toString());
		this.type
				.setText(queryGuestRoomInfoTable.getValueAt(row, 2).toString());
		this.state.setText(queryGuestRoomInfoTable.getValueAt(row, 3)
				.toString());
		this.id.setText(queryGuestRoomInfoTable.getValueAt(row, 0).toString());
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton editBtn;
	private javax.swing.JTextField id;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable queryGuestRoomInfoTable;
	private javax.swing.JTextField reRoomNum;
	private javax.swing.JTextField roomNum;
	private javax.swing.JButton search;
	private javax.swing.JTextField state;
	private javax.swing.JTextField type;
	// End of variables declaration//GEN-END:variables

}